### ISSUE TITLE
Use os.path.join instead of hardcoding '\\'

### ISSUE THREAD

**Issue by vishnugt** [rajeshias/All-repo-non-code-data-downloader#2]
https://github.com/rajeshias/All-repo-non-code-data-downloader/blob/b0dcbbb2ca4673ed2936dc2d3ca10ef6ff4086b8/main.py#L79

Hardcoding '\\' is not a good way, because it won't work in linux based OSes, always prefer os.path.join
![image](https://user-images.githubusercontent.com/7014475/120514624-2034e380-c3eb-11eb-96b0-920f34c8beac.png)

**Comment by rajeshias** [comment]
not only there, there are multiple places, I used '\\' . I will revamp all those places

**Comment by rajeshias** [comment]
Used os.path.join() for all path mentions!
