### ISSUE TITLE
Incrementally write out repositories

### ISSUE THREAD

**Issue by suchow** [rajeshias/All-repo-non-code-data-downloader#4]
Currently, the script builds up all the data in `repo_data`, `issues_data`, and `pr_data` and then writes out all the data afterwards, only once all the data is collected. This scales poorly with the number of repositories, especially when the script is used to iterate over ALL GitHub repos. Instead, the data for a particular repo should be retrieved and then immediately written out to disk, with those variables then being reset for the next repo.

**Comment by rajeshias** [comment]
More memory efficient, and every iteration will be written in disk
