### ISSUE TITLE
Iterate over all public GitHub repos

### ISSUE THREAD

**Issue by suchow** [rajeshias/All-repo-non-code-data-downloader#5]
The current code has many options that are useful for testing. However, the goal of the project is to iterate over all public repos. Therefore, the first 50 or so lines of code that handle user input to adjust the scope of the scraping is uneeded. Instead, the code should iterate over the repos provided by the iteratable `g.get_repos()`.

**Comment by rajeshias** [comment]
got it!

**Comment by rajeshias** [comment]
redundant choices in menu removed
